In [1]:
import pandas as pd
import sqlite3
fifa=pd.read_csv("../data/fifa_world_cup_2026_player_performance.csv")
print("FIFA CSV file imported successfully.")
print("Rows:",len(fifa))
print("Columns:",len(fifa.columns))

FIFA CSV file imported successfully.
Rows: 54600
Columns: 75

In [2]:
display(fifa.head())

  player_id       player_name  ...  player_of_match_awards tournament_rating
0    P00055        Rodri Fati  ...                       0               5.8
1    P00070   Ansu Le Normand  ...                       0               5.5
2    P00066        Gavi Ramos  ...                       0               8.4
3    P00073     Pedro Cubarsi  ...                       0               6.7
4    P00059  Alvaro Oyarzabal  ...                       0               5.7

[5 rows x 75 columns]

In [3]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 75 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  object
 1   player_name               54600 non-null  object
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  object
 4   team                      54600 non-null  object
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  object
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  object
 10  club_name                 54600 non-null  object
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  object
 13  match_date                54600 non-null  object
 14  stadium                   54600 non-null  object
 15  city                      54600 non-null  object
 16  opponent_team             54600 non-null  object
 17  tournament_stage          54600 non-null  object
 18  match_result              54600 non-null  object
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  int64
 22  goals                     54600 non-null  int64
 23  assists                   54600 non-null  int64
 24  shots                     54600 non-null  int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  int64
 47  red_cards                 54600 non-null  int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
dtypes: float64(18), int64(43), object(14)
memory usage: 31.2+ MB

In [4]:
display(fifa.describe(include="all").T)

                            count unique  ...    75%    max
player_id                   54600   1248  ...    NaN    NaN
player_name                 54600   1245  ...    NaN    NaN
age                       54600.0    NaN  ...   29.0   39.0
nationality                 54600     48  ...    NaN    NaN
team                        54600     48  ...    NaN    NaN
...                           ...    ...  ...    ...    ...
total_goals_tournament    54600.0    NaN  ...    1.0   10.0
total_assists_tournament  54600.0    NaN  ...    1.0    8.0
total_minutes_tournament  54600.0    NaN  ...  359.0  615.0
player_of_match_awards    54600.0    NaN  ...    0.0    4.0
tournament_rating         54600.0    NaN  ...    6.4    9.5

[75 rows x 11 columns]

In [5]:
fifa_sample=fifa.head(20); fifa_sample.to_excel("fifa_sample.xlsx",index=False)
fifa_excel=pd.read_excel("fifa_sample.xlsx")
print("Excel file imported successfully."); display(fifa_excel.head())

Excel file imported successfully.

  player_id       player_name  ...  player_of_match_awards tournament_rating
0    P00055        Rodri Fati  ...                       0               5.8
1    P00070   Ansu Le Normand  ...                       0               5.5
2    P00066        Gavi Ramos  ...                       0               8.4
3    P00073     Pedro Cubarsi  ...                       0               6.7
4    P00059  Alvaro Oyarzabal  ...                       0               5.7

[5 rows x 75 columns]

In [6]:
conn=sqlite3.connect("fifa_data.db"); fifa_sample.to_sql("fifa_players",conn,if_exists="replace",index=False)
fifa_sql=pd.read_sql("SELECT * FROM fifa_players LIMIT 5",conn)
print("SQL data imported successfully."); display(fifa_sql); conn.close()

SQL data imported successfully.

  player_id       player_name  ...  player_of_match_awards tournament_rating
0    P00055        Rodri Fati  ...                       0               5.8
1    P00070   Ansu Le Normand  ...                       0               5.5
2    P00066        Gavi Ramos  ...                       0               8.4
3    P00073     Pedro Cubarsi  ...                       0               6.7
4    P00059  Alvaro Oyarzabal  ...                       0               5.7

[5 rows x 75 columns]

In [7]:
print("Web import syntax demonstrated using pd.read_csv(url).")
print("Example: url = \"https://example.com/fifa_data.csv\"; web_data = pd.read_csv(url)")

Web import syntax demonstrated using pd.read_csv(url).
Example: url = "https://example.com/fifa_data.csv"; web_data = pd.read_csv(url)

In [8]:
fifa_sample.to_csv("fifa_export.csv",index=False); print("FIFA CSV file exported successfully."); print("Exported rows:",len(fifa_sample))

FIFA CSV file exported successfully.
Exported rows: 20

In [9]:
fifa_sample.to_excel("fifa_export.xlsx",index=False); print("FIFA Excel file exported successfully."); print("Exported rows:",len(fifa_sample))

FIFA Excel file exported successfully.
Exported rows: 20

In [10]:
fifa_sample.to_json("fifa_export.json",orient="records",indent=2); print("FIFA JSON file exported successfully."); print("Exported records:",len(fifa_sample))

FIFA JSON file exported successfully.
Exported records: 20

In [11]:
conn=sqlite3.connect("fifa_export.db"); fifa_sample.to_sql("fifa_data",conn,if_exists="replace",index=False); count=pd.read_sql("SELECT COUNT(*) AS row_count FROM fifa_data",conn); print("FIFA data exported to SQLite successfully."); display(count); conn.close()

FIFA data exported to SQLite successfully.

   row_count
0         20

In [12]:
print("Dataset shape:",fifa.shape)
print("Number of players:",fifa["player_id"].nunique())
print("Teams:",fifa["team"].nunique())
print("\nColumns:"); print(fifa.columns.tolist())

Dataset shape: (54600, 75)
Number of players: 1248
Teams: 48

Columns:
['player_id', 'player_name', 'age', 'nationality', 'team', 'jersey_number', 'position', 'height_cm', 'weight_kg', 'preferred_foot', 'club_name', 'market_value_eur', 'match_id', 'match_date', 'stadium', 'city', 'opponent_team', 'tournament_stage', 'match_result', 'goals_team', 'goals_opponent', 'minutes_played', 'goals', 'assists', 'shots', 'shots_on_target', 'expected_goals_xg', 'expected_assists_xa', 'key_passes', 'successful_passes', 'total_passes', 'pass_accuracy', 'dribbles_attempted', 'successful_dribbles', 'crosses', 'successful_crosses', 'tackles', 'interceptions', 'clearances', 'blocks', 'aerial_duels_won', 'aerial_duels_lost', 'recoveries', 'defensive_actions', 'fouls_committed', 'fouls_suffered', 'yellow_cards', 'red_cards', 'offsides', 'saves', 'save_percentage', 'punches', 'clean_sheet', 'goals_conceded', 'penalty_saves', 'distance_covered_km', 'sprint_distance_km', 'top_speed_kmh', 'accelerations', 'decelerations', 'stamina_score', 'player_rating', 'performance_score', 'offensive_contribution', 'defensive_contribution', 'possession_impact', 'pressure_resistance', 'creativity_score', 'consistency_score', 'clutch_performance_score', 'total_goals_tournament', 'total_assists_tournament', 'total_minutes_tournament', 'player_of_match_awards', 'tournament_rating']